<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSI" ignored="0" name="Test" tests="4" failures="1" timestamp="2020-09-23T20:58:41 CDT" time="7.69" errors="0">
  <testcase name="test3" time="0.017" classname="com.review.class01.AnnotationRecap">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [25] but found [35]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [25] but found [35]
at com.review.class01.AnnotationRecap.test3(AnnotationRecap.java:53)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.0" classname="com.review.class01.AnnotationRecap">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.002" classname="com.review.class01.AnnotationRecap"/>
  <testcase name="loginValitation" time="0.001" classname="com.review.class01.Login"/>
</testsuite> <!-- Test -->
